Add empty CHANGELOG.md
FuelLabs/sway-standards pull request #104
Opened 2024-06-06 08:55 UTC by bitzoic

## Type of change

- New feature

## Changes

The following changes have been made:

- Adds CHANGELOG.md to begin tracking changes to the repository
- Updates the Pull Request template to include require an update to the CHANGELOG.md file

## Related Issues

Closes #92 

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.

2024-06-06 14:39 UTC, K1-R1 requested changes
The change log has 2 breaking sections

2024-06-06 14:39 UTC, K1-R1 commented on CHANGELOG.md
> +- Some breaking fix here 3
```suggestion
- Some breaking change here 1
```

2024-06-06 14:39 UTC, K1-R1 commented on CHANGELOG.md
> +- Some breaking fix here 4
```suggestion
- Some breaking change here 2
```

2024-06-07 05:33 UTC, SwayStar123 approved these changes

2024-06-10 16:23 UTC, K1-R1 approved these changes

2024-06-11 04:43 UTC, merged