SRC-6 example contract does not update managed assets
FuelLabs/sway-standards pull request #122
Opened 2024-07-08 10:55 UTC by bitzoic

## Type of change

- Bug fix

## Changes

The following changes have been made:

- There is a critical flaw in the SRC-6 example contract where the managed assets is not updated with assets are withdrawn. This can be exploited to drain the contract. This PR resolves this critical bug.

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.
- [ ] I have updated the changelog to reflect the changes on this PR.

2024-07-08 11:09 UTC, SwayStar123 requested changes

2024-07-08 11:09 UTC, SwayStar123 commented on examples/src6-vault/multi_asset_vault/src/main.sw
> +        vault_info.managed_assets = vault_info.managed_assets - shares;
you need to set the storage here right? AFAIK the mut doesnt make the storage mutate aswell

2024-07-08 11:09 UTC, SwayStar123 commented on examples/src6-vault/single_asset_vault/src/main.sw
> +        vault_info.managed_assets = vault_info.managed_assets - shares;
same here

2024-07-08 11:41 UTC, bitzoic commented on examples/src6-vault/multi_asset_vault/src/main.sw
> +        vault_info.managed_assets = vault_info.managed_assets - shares;
`mut` is required because a subtraction occurs on line 85.

2024-07-08 12:02 UTC, SwayStar123 commented on examples/src6-vault/multi_asset_vault/src/main.sw
> +        vault_info.managed_assets = vault_info.managed_assets - shares;
but does the change reflect in storage?

2024-07-08 14:19 UTC, SwayStar123 submitted a review, later dismissed

2024-07-08 14:21 UTC, K1-R1 approved these changes

2024-07-09 12:36 UTC, SwayStar123 approved these changes

2024-07-09 14:01 UTC, K1-R1 approved these changes

2024-07-09 14:24 UTC, merged