Add required logging of SRC-20 to SRC-6 examples
FuelLabs/sway-standards pull request #151
Opened 2024-09-10 05:44 UTC by SwayStar123

## Type of change

- Bug fix

## Changes

The following changes have been made:

- Adds logging of values of SRC-20 whenever they are updated in SRC-6 examples
- Formats the examples of src6
- Fixes some inline comments

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.
- [ ] I have updated the changelog to reflect the changes on this PR.

2024-09-11 11:52 UTC, bitzoic requested changes

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/single_asset_single_sub_vault/src/main.sw
> +        storage
You already read this from storage on line 279

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/single_asset_single_sub_vault/src/main.sw
> +        storage
You already read this from storage on line 255

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/multi_asset_vault/src/main.sw
> +        storage
You already have some of this from line 301, no need to make another expensive storage call

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/multi_asset_vault/src/main.sw
> +        storage
This is already fetched

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/single_asset_single_sub_vault/src/main.sw
> +    #[storage(read)]
This is labeled "set" but only reads from storage. Where is the contract setting this information?

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/multi_asset_vault/src/main.sw
> +    fn set_src20_data(
This function is incomplete

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/single_asset_vault/src/main.sw
> +    fn set_src20_data(
Again, incomplete

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/single_asset_vault/src/main.sw
> +        storage
Already read

2024-09-11 11:52 UTC, bitzoic commented on examples/src6-vault/single_asset_vault/src/main.sw
> +        storage
Unnecessary read

2024-09-11 12:05 UTC, SwayStar123 commented on examples/src6-vault/single_asset_single_sub_vault/src/main.sw
> +    #[storage(read)]
Right, i copy pasted this from the src20 examples, which are the same, those should be fixed too then

2024-09-16 16:03 UTC, K1-R1 approved these changes

2024-09-17 05:21 UTC, bitzoic approved these changes

2024-09-17 05:21 UTC, merged