Add inline docs examples to SRC-6 abi
FuelLabs/sway-standards pull request #152
Opened 2024-09-10 06:12 UTC by SwayStar123

## Type of change

- Documentation

## Changes

The following changes have been made:

- Adds examples to the inline docs in SRC-6 abi

Closes #\<issue number\>

## Checklist

- [ ] I have linked to any relevant issues.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation where relevant (API docs, the reference, and the Sway book).
   - [ ] If my change requires substantial documentation changes, I have [requested support from the DevRel team](https://github.com/FuelLabs/devrel-requests/issues/new/choose)
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added (or requested a maintainer to add) the necessary `Breaking*` or `New Feature` labels where relevant.
- [ ] I have done my best to ensure that my PR adheres to [the Fuel Labs Code Review Standards](https://github.com/FuelLabs/rfcs/blob/master/text/code-standards/external-contributors.md).
- [ ] I have requested a review from the relevant team or maintainers.
- [ ] I have updated the changelog to reflect the changes on this PR.

2024-09-11 11:54 UTC, bitzoic requested changes

2024-09-11 11:54 UTC, bitzoic commented on CHANGELOG.md
> +- [#152](https://github.com/FuelLabs/sway-standards/pull/152) Adds inline documentation examples to the SRC-6 standard.
This is not included in v0.6.1 but unreleased

2024-09-11 11:54 UTC, bitzoic commented on standards/src/src6.sw
> +    ///         asset_id: asset_id.bits()
Is bits() correct? I have not compile this to verify

2024-09-11 12:30 UTC, SwayStar123 commented on standards/src/src6.sw
> +    ///         asset_id: asset_id.bits()
https://docs.fuel.network/docs/sway/sway-program-types/smart_contracts/

2024-09-16 16:04 UTC, K1-R1 approved these changes

2024-09-17 05:21 UTC, bitzoic approved these changes

2024-09-17 05:21 UTC, merged