initial commit
FuelLabs/sway-standards pull request #24
Opened 2023-09-19 11:33 UTC by SwayStar123

## Type of change

- New feature

## Changes

The following changes have been made:

- Add vault standard

2023-09-26 08:05 UTC, bitzoic requested changes

2023-09-26 08:05 UTC, bitzoic commented on standards/src_6/README.md
> +# Abstract
```suggestion
# Abstract

```
Same for all the other headers

2023-09-26 14:47 UTC, Braqzen reviewed
Standard uses the images for SRC-5 instead of newly created images for SRC-6

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +
```suggestion
```

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
Wondering about the `asset` being stored as an `AssetId` since it is derived from a contract id and a sub id. Do we want additional info to track where it came from... contract id, sub id, or is this okay for a vault?

Since the IDs are unique it should be fine but is there a case where we would be interested in that data?

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    // Deposit/Withdrawal
```suggestion
```

No value added, just more span similar to the logs comment at the top

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    /// * If the amount of assets is zero.
```suggestion
    /// * If the amount of assets being forwarded from the contract is zero.
```

Maybe reword again. Idea is to make it clear that if there is an insufficient number to forward then we revert. If that is the case then I imagine that this shouldn't mention 0 but instead if the contract holds less than the amount that is equivalent to the deposit.

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    /// * The user crosses any global or user specific deposit limits.
Why would a vault have a deposit limit?
Remove this entirely?

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    /// * If the transferred shares do not corresspond to the given asset.
I don't understand how the shares may not correspond to an asset if we are internally tracking this... no?

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    // Accounting
```suggestion
```

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    /// Returns the amount of managed assets of the given asset.
The whole `managed` does not make sense to me. It seems like this is a getter for the amount of an asset in a contract. Rename to `assets`?

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    /// * For any reason a deposit would revert.
This is a poor comment. It does not inform the user in any way. It's too broad. Also, isn't this supposed to return 0 if it would not return a value i.e. revert? Similar to withdrawal below

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    // Deposit/Withdrawal Limits
```suggestion
```

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    fn max_withdrawable(asset: AssetId) -> Option<u64>;
I don't think we should enforce this as a standard. The implementation here is also subjective. Is it a 1 time max or a moving window period meaning within each 24h you can withdraw / deposit X amount and it accrues over time?
I would just remove

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/README.md
> +Token vaults allow users to own shares of variable amount of assets, such as lending protocols which may have growing assets due to profits from interest. This pattern is highly useful and would grea
```suggestion

Token vaults allow users to own shares of variable amount of assets, such as lending protocols which may have growing assets due to profits from interest. This pattern is highly useful and would greatly benefit from standardisation.
```

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/README.md
> +This function takes the receiver's identity as an argument and returns the amount of shares minted.
Instead of `returns` I would explicitly mention that it transfers the shares of some sub id or whatever. `returns` implies it may be just a number returned from a contract call (getter)

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/README.md
> +MUST NOT revert under any circumstances.
I believe there is documentation below which states that it may revert...

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/README.md
> +```
```suggestion
```rust
```

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/README.md
> +`caller` has called the `deposit` method sending `assets` assets of the `asset` AssetId, in exchange for `shares` shares sent to the receiver `receiver`
```suggestion

`caller` has called the `deposit` method sending `assets` assets of the `asset` AssetId, in exchange for `shares` shares sent to the receiver `receiver`
```

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/README.md
> +```
```suggestion
```rust
```

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/README.md
> +`caller` has called the `withdraw` method sending `shares` shares in exchange for `assets` assets of the `asset` AssetId to the receiver `receiver`
```suggestion

`caller` has called the `withdraw` method sending `shares` shares in exchange for `assets` assets of the `asset` AssetId to the receiver `receiver`
```

2023-09-26 14:47 UTC, Braqzen commented on standards/src_6/README.md
> +The ABI discussed is simple and covers the known use cases of token vaults while allowing safe implementations
```suggestion

The ABI discussed covers the known use cases of token vaults while allowing safe implementations
```

2023-09-26 18:41 UTC, SwayStar123 commented on standards/src_6/src/src_6.sw
> +    /// * If the transferred shares do not corresspond to the given asset.
See the example implementation

2023-09-26 18:42 UTC, SwayStar123 commented on standards/src_6/src/src_6.sw
> +    /// Returns the amount of managed assets of the given asset.
A vault can be managing assets that it does not own directly at the moment, ie deposited in another dapp or something

2023-09-26 19:03 UTC, SwayStar123 commented on standards/src_6/src/src_6.sw
> +    /// * The user crosses any global or user specific deposit limits.
Its an extremely common pattern to have limits on vaults in Ethereum? For example if the contract is in a beta or a prerelease it can have limits to mitigate losses from hacks. Depositing to vaults is also sometimes locked behind nfts, which only allows you to deposit a certain quantity

2023-09-29 16:16 UTC, dmihal reviewed
Should we include methods like `fn underlying_asset(asset: AssetId) -> Option<AssetId>` and `fn vault_asset(underlying: AssetId) -> Option<AssetId>` to allow converting between vaults & underlying?

Alternatively, we could just delegate this task to the indexer, having it index `Deposit` events.

2023-09-29 16:16 UTC, dmihal commented on standards/src_6/README.md
> +### `fn preview_deposit(asset: AssetId, assets: u64) -> u64`
Will this always be the same as `convert_to_shares`?

2023-09-29 16:16 UTC, dmihal commented on standards/src_6/README.md
> +### `fn preview_withdraw(asset: AssetId, shares: u64) -> u64`
Will this always be the same as `convert_to_assets`?

2023-09-29 16:16 UTC, dmihal commented on standards/src_6/README.md
> +Incorrect implementation of token vaults could allow attackers to steal underlying assets. It is recommended to properly audit any code using this standard to ensure exploits are not possible.
I wonder if we should include something about how a vault can "lie" about the underlying?

Ex, if a vault says some asset represents USDC, there's no guarantee that the vault _actually_ represents USDC (may be a consideration for wallets)

2023-09-29 16:16 UTC, dmihal commented on standards/src_6/src/src_6.sw
> +    fn max_withdrawable(asset: AssetId) -> Option<u64>;
I think it's worth keeping, there's no implied "time window", it's more like how much can be deposited/withdrawn right now. It's useful for lending markets, because you're basically saying that "X vault tokens represent Y underlying tokens, but only Z can be withdrawn right now (because the rest are lent out)"

2023-09-29 16:16 UTC, dmihal commented on standards/src_6/src/src_6.sw
I don't think a vault would care about the underlying contractId/subId of the underlying token, AssetId should be sufficent

2023-09-29 17:55 UTC, SwayStar123 commented on standards/src_6/src/src_6.sw
> +    /// * If the transferred shares do not corresspond to the given asset.
In the example implementation, i take the AssetId of the deposited asset as the sub id, for minting of share tokens. So if any shares of AssetId =/= `sha256(contract_id, deposited_asset_asset_id)` are transferred, it reverts, with this line
`require(msg_asset_id() == AssetId::new(ContractId::this(), asset.into()), "INVALID_ASSET_ID");`

In other words, if the transferred shares dont correspond to the given asset, then the transaction will revert. Im not sure what the confusion here is, obviously we dont want people depositing shares of one asset and withdrawing another.

2023-10-03 10:40 UTC, SwayStar123 commented on standards/src_6/src/src_6.sw
> +    /// * If the amount of assets is zero.
What? This is the deposit function, its just reverting if no assets are forwarded *to* the contract.

2023-10-03 10:42 UTC, SwayStar123 commented on standards/src_6/src/src_6.sw
> +    /// * For any reason a deposit would revert.
What makes you think its supposed to return 0? I dont think i mentioned that anywhere

2023-10-03 10:47 UTC, SwayStar123 commented on standards/src_6/README.md
> +MUST NOT revert under any circumstances.
Where?

2023-10-03 11:30 UTC, SwayStar123 commented on standards/src_6/README.md
> +### `fn preview_deposit(asset: AssetId, assets: u64) -> u64`
No, convert_to_shares wont account for any slippage and will not revert. Basically ideal conditions. the preview functions can revert for any reason the main function will revert, and they return the amount of assets/shares that would be received if it was a withdraw/deposit call instead (in the exact same context and conditions)

2023-10-03 14:53 UTC, Braqzen commented on standards/src_6/src/src_6.sw
> +    /// * For any reason a deposit would revert.
Thinking about usage.
If you attempt to view what value it would return it shouldn't crash. It should return some value such as an error or 0 if that 0 makes sense as a default.

2023-10-03 14:54 UTC, Braqzen commented on standards/src_6/README.md
> +MUST NOT revert under any circumstances.
Without having to look over all the work I imagine I've look at the docs in the code itself

2023-10-10 10:52 UTC, SwayStar123 commented on standards/src_6/README.md
> +MUST NOT revert under any circumstances.
Okay well i didnt find any such documentation so im just gonna assume you misread something unless you manage to find it

2023-11-14 13:52 UTC, bitzoic requested changes
For your example, there should be one example where the vault handles a single asset and one where it handles multiple assets. Take a look at the other examples to see the difference between single vs multi. There should also be inline docs for the functions that apply to the SRC-6 standard. Try to remove all helper functions, the purpose is to be so dead simple that abstraction shouldn't be needed. It could also benefit from some comments.

Your logo is the SRC-5 logo.

Should helper function be defined in a standard? If they aren't critical to the functionality it seems unnecessary.

2023-11-14 13:52 UTC, bitzoic commented on examples/src_6/simple_vault/src/main.sw
> +        Option::Some(18_446_744_073_709_551_615 - managed_assets(asset)) // This is the max value of u64 minus the current managed_assets. Ensures that the sum will always be lower than u64::MAX.
There's also no check for this in the `deposit` function

2023-11-14 13:52 UTC, bitzoic commented on standards/src_6/README.md
> +## Required public functions
```suggestion
## Required public functions

```
Add new lines below as well

2023-11-14 13:52 UTC, bitzoic commented on standards/src_6/README.md
> +
```suggestion
# Example ABI

sway
abi SRC6 {
/// Fill in
}

# Example Implementation

## Single (link)

Desc.

## Muti (link)

Desc.
```

2023-11-14 13:52 UTC, bitzoic commented on standards/src_6/README.md
> +The ABI discussed is simple and covers the known use cases of token vaults while allowing safe implementations
```suggestion
The ABI discussed covers the known use cases of token vaults while allowing safe implementations.
```

2023-11-14 13:52 UTC, bitzoic commented on standards/src_6/README.md
> +# Backwards compatibility
```suggestion
# Backwards Compatibility
```

2023-11-14 13:52 UTC, bitzoic commented on standards/src_6/README.md
> +MUST return an Option::Some of the AssetId of the vault shares for the given asset and sub vault, if the given asset is supported.
```suggestion
MUST return `Some(AssetId)` of the vault shares for the given asset and sub vault, if the given asset is supported.
```
This should be applied to multiple lines

2023-11-14 13:52 UTC, bitzoic commented on standards/src_6/README.md
> +### `fn max_withdrawable(asset: AssetId, sub_id: SubId) -> Option<u64>`
Since this is just a helper function I doubt whether this should even be included

2023-11-14 13:52 UTC, bitzoic commented on standards/src_6/README.md
> +MUST send `preview_withdraw(redeemed_shares)` amount of assets to `receiver`.
What is `preview_withdraw`????

2023-11-30 08:14 UTC, SwayStar123 commented on examples/src_6/simple_vault/src/main.sw
> +pub fn _mint(
How is this an external function? I dont see any problem with having the function defined here, its just making the main function more readable

2023-11-30 08:21 UTC, SwayStar123 commented on examples/src_6/simple_vault/src/main.sw
> +fn vault_asset_id(asset: AssetId, sub_id: SubId) -> (AssetId, SubId) {
Why?

2023-11-30 08:21 UTC, SwayStar123 commented on examples/src_6/simple_vault/src/main.sw
> +fn managed_assets(share_asset: AssetId) -> u64 {
Why?

2023-11-30 08:28 UTC, SwayStar123 commented on standards/src_6/README.md
> +### `fn max_withdrawable(asset: AssetId, sub_id: SubId) -> Option<u64>`
Wdym? Its a abi function

2023-11-30 12:49 UTC, dmihal commented on standards/src_6/README.md
> +### `fn convert_to_shares(asset: AssetId, sub_id: SubId, assets: u64) -> Option<u64>`
Can this be removed in favor of just simulating deposit?

2023-12-01 16:20 UTC, SwayStar123 commented on examples/src_6/simple_vault/src/main.sw
> +        Option::Some(18_446_744_073_709_551_615 - managed_assets(asset)) // This is the max value of u64 minus the current managed_assets. Ensures that the sum will always be lower than u64::MAX.
There is no way for a contract to own more than u64::MAX tokens

2023-12-01 16:22 UTC, SwayStar123 commented on examples/src_6/simple_vault/src/main.sw
> +pub struct VaultInfo {
I would say it makes the code alot more neater, i dont think we should make the code harder to read in aim of simplicity

2023-12-01 16:33 UTC, SwayStar123 commented on standards/src_6/README.md
> +/// Event logged when a deposit is made.
Im confused, thats also just the specification enum, just without comments

2023-12-05 12:25 UTC, dmihal commented on standards/src_6/src/src_6.sw
> +    fn asset_of_vault(vault_asset_id: AssetId) -> Option<(AssetId, SubId)>;
Should this be removed in favor of using the indexer?

2023-12-05 19:06 UTC, Braqzen reviewed
Quick shallow review for feedback. Will spend more time next time when comments are addressed

2023-12-06 17:08 UTC, SwayStar123 commented on examples/src_6/single_token_single_sub_vault/src/main.sw
Yes, in this standard you can have multiple vaults for the same underlying token, by specifying a sub_id for a sub vault

2023-12-07 16:43 UTC, Braqzen approved these changes
Formatting in CI.

utACK

2023-12-07 21:14 UTC, Braqzen approved these changes

2023-12-07 21:14 UTC, Braqzen commented on examples/src_6/multi_token_vault/src/main.sw
> +    },
```suggestion
    token::transfer
```

small nit throughout files

2023-12-08 14:38 UTC, Braqzen submitted a review, later dismissed

2023-12-12 08:43 UTC, bitzoic requested changes
Went through the `deposit()` function, mostly just making things more verbose but some changes here and there. The same changes should be applied to all the function definitions

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +Token vaults have been thoroughly explored on Ethereum and with [EIP 4626](https://eips.ethereum.org/EIPS/eip-4626) they have their own standard for it. However as Fuel's native assets are fundamenta
```suggestion
Token vaults have been thoroughly explored on Ethereum and with [EIP 4626](https://eips.ethereum.org/EIPS/eip-4626) they have their own standard for it. However as Fuel's [Native Assets](https://docs.fuel.network/docs/sway/blockchain-development/native_assets) are fundamentally different from Ethereum's ERC-20 tokens, the implementation will differ, but the interface may be used as a reference.
```

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +Method that allows depositing of the underlying asset in exchange for shares of the vault.
```suggestion
This function MUST allow for depositing of the underlying asset in exchange for shares of the vault.
```

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +This function takes the receiver's identity and the sub_id of the sub vault as an argument and returns the amount of shares minted to the receiver.
```suggestion
This function takes the `receiver` Identity and the SubId `sub_id` of the sub-vault as an argument and returns the amount of shares minted to the receiver.
```

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +MUST revert if any unaccepted AssetId is forwarded.
```suggestion
This function MUST revert if any unaccepted asset for a particular sub-vault is sent.
```

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +MUST increase `managed_assets` by amount of deposited assets (through any means including `std::context::this_balance(ASSET_ID)` if applicable).
```suggestion
This function MUST increment `managed_assets` by the amount of deposited assets (through any means including `std::context::this_balance(ASSET_ID)` if applicable).
```
What is `managed_assets`. Reading chronologically through this standard this is the first time I'm coming across this. Are we standardizing variables?

Could we state that this function instead 
`This function must keep track of deposits` instead?

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +MUST mint a token representing the pro-rata share of the vault, with the AssetId of `sha256((asset, sub_id))`, a hash of the AssetId of the deposited asset, and the `sub_id` of the vault.
```suggestion
This function MUST mint an asset representing the pro-rata share of the vault, with the SubId of the `sha256((asset, sub_id))` digest, where `asset` is the AssetId of the deposited asset and the `sub_id` is the id of the vault.
```

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +MUST increase `total_supply` of the share's AssetId by newly minted shares.
```suggestion
This function MUST increase the [SRC-20](https://github.com/FuelLabs/sway-standards/tree/master/standards/src_20) total supply of the sub-vault's asset.
```

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +MUST increase `total_assets` by one if the the AssetId is minted for the first time.
```suggestion
MUST increase the [SRC-20](https://github.com/FuelLabs/sway-standards/tree/master/standards/src_20) total assets by one if the sub-vault is minted for the first time.
```

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +MUST emit a `Deposit` log.
```suggestion
This function MUST emit a `Deposit` log.
```

2023-12-12 08:43 UTC, bitzoic commented on standards/src_6/README.md
> +MUST return amount of minted shares.
```suggestion
This function MUST return the amount of minted shares.
```

2023-12-12 08:51 UTC, SwayStar123 commented on standards/src_6/README.md
> +MUST increase `total_assets` by one if the the AssetId is minted for the first time.
doesnt make sense to say a sub vault is minted. Is "sub-vault share asset" too verbose?

2023-12-12 10:19 UTC, bitzoic requested changes

2023-12-12 10:19 UTC, bitzoic commented on standards/src_6/README.md
> +/// Event logged when a deposit is made.
```suggestion
### Deposit

The `Deposit` log SHALL have the following fields.

#### - `caller`: Identity

The `caller` field MUST represent the Identity which called the deposit function.

#### - `receiver`: Identity

The `receiver` field MUST represent the Identity which received the vault shares. 

#### - `asset`: AssetId

The `asset` field MUST represent the AssetId of the asset which was deposited into the vault.

#### - `sub_id`: SubId

The `sub_id` field MUST represent the SubId of the vault which was deposited into.

#### - `deposit_amount`: u64

The `deposit_amount` field MUST represent the u64 amount of assets deposited into the vault.

#### - `shares`: u64

The `shares` field MUST represent the u64 amount of shares minted.
```

2023-12-12 10:19 UTC, bitzoic commented on standards/src_6/README.md
> +`caller` has called the `deposit` method sending `assets` assets of the `asset` AssetId to the subvault of `sub_id`, in exchange for `shares` shares sent to the receiver `receiver`
This can be removed if you define the struct in the comment above

2023-12-12 10:19 UTC, bitzoic commented on standards/src_6/README.md
> +The `Deposit` struct MUST be logged whenever new shares are minted via the `deposit` method
This can be moved under the ### Deposit header or remove since it's defined in the `deposit()` function.

2023-12-12 10:19 UTC, bitzoic commented on standards/src_6/README.md
> +/// Event logged when a withdrawal is made.
```suggestion
### Withdraw

The `Withdraw` log SHALL have the following fields.

#### - `caller`: Identity

The `caller` field MUST represent the Identity which called the withdraw function.

#### - `receiver`: Identity

The `receiver` field MUST represent the Identity which received the withdrawn assets.

#### - `withdawn_asset`: AssetId

The `deposit_asset` field MUST represent the AssetId of the asset that was withdrawn.

#### - `withdrawn_id`: SubId

The `vault_id` field MUST represent the SubId of the vault from which was withdrawn.

#### - `withdraw_amount`: u64

The `withdraw_amount` field MUST represent the u64 amount of tokens withdrawn.

#### - `shares`: u64

The `shares` field MUST represent the u64 amount of shares burned.

```

2023-12-12 10:19 UTC, bitzoic commented on standards/src_6/README.md
> +`caller` has called the `withdraw` method sending `shares` shares in exchange for `assets` assets of the `asset` AssetId from the subvault of `sub_id` to the receiver `receiver`
This can be removed

2023-12-12 10:19 UTC, bitzoic commented on standards/src_6/README.md
> +The `Withdraw` struct MUST be logged whenever shares are redeemed for assets via the `withdraw` method
Removed or move up to the ### Deposit section

2023-12-12 10:19 UTC, bitzoic commented on standards/src_6/README.md
> +The ABI discussed and covers the known use cases of token vaults while allowing safe implementations
```suggestion
The ABI discussed covers the known use cases of token vaults while allowing safe implementations.
```

2023-12-12 10:19 UTC, bitzoic commented on standards/src_6/README.md
> +This standard is fully compatible with the SRC-20 standard
```suggestion
This standard is fully compatible with the [SRC-20 standard](https://github.com/FuelLabs/sway-standards/tree/master/standards/src_20).
```

2023-12-12 14:44 UTC, Braqzen commented
Tag me when ready for a final review

2023-12-15 10:21 UTC, SwayStar123 commented on standards/src_6/README.md
> +Method that returns the total assets under management by vault. Includes assets controlled by the vault but not directly possessed by vault.
Vault strategies can utilize deposited assets in other dapps and such

2023-12-15 11:14 UTC, bitzoic approved these changes
:shipit:

2023-12-15 11:15 UTC, SwayStar123 commented
@Braqzen

2023-12-15 11:38 UTC, Braqzen approved these changes

2023-12-15 11:44 UTC, merged