Vault standard with subvaults
FuelLabs/sway-standards pull request #28
Opened 2023-10-17 11:15 UTC by SwayStar123

## Type of change

- Improvement (refactoring, restructuring repository, cleaning tech debt, ...)

## Changes

The following changes have been made:

- Adds subvaults feature to the vault standard

2023-10-17 11:37 UTC, dmihal commented on standards/src_6/README.md
> +### `fn asset_of_vault(vault_asset_id: AssetId) -> Option<AssetId>`
Will require storing a mapping in state? Does it make more sense to do this at the indexer layer?

Also, should we return the subId?

2023-10-30 18:35 UTC, SwayStar123 commented
@dmihal @bitzoic Formatter breaks due to the example. Wat do?

2023-10-31 12:41 UTC, dmihal requested changes

2023-10-31 12:41 UTC, dmihal commented on standards/src_6/examples/simple_vault.sw
> +impl SRC20 for Contract {
Move below the SRC6 block

2023-10-31 12:44 UTC, merged