Src11 security information standard
FuelLabs/sway-standards pull request #55
Opened 2024-01-23 14:18 UTC by SwayStar123

## Type of change

- New feature

## Changes

The following changes have been made:

- The new security information standard has been added.

2024-02-13 04:36 UTC, bitzoic requested changes
I would break the required function section and the `SecurityInformation` struct into two parts. The function defining that it returns the struct and then the `SecurityInformation` section defining the struct's contents and any optional parameters.

The header logo in the README is using the Vault Standards README, this must be updated.

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +White hat hackers may find bugs or exploits in contracts which they want to report to the project for safeguarding of funds. It is not immedietely obvious from a ContractId, who the right person to c
```suggestion
White hat hackers may find bugs or exploits in contracts that they want to report to the project for safeguarding of funds. It is not immediately obvious from a ContractId, who the right person to contact is. This standard aims to make the process of bug reporting as smooth as possible
```

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +The [security.txt](https://github.com/neodyme-labs/solana-security-txt) library for solana has explored this idea. This standard takes inspiration from the library, with some changes.
```suggestion
The [security.txt](https://github.com/neodyme-labs/solana-security-txt) library for Solana has explored this idea. This standard takes inspiration from the library, with some changes.
```

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +This function takes no input parameters and returns a struct containing contact information for the project owners, information regarding the bug bounty program, other information related to security
```suggestion
This function takes no input parameters and returns a struct containing contact information for the project owners, information regarding the bug bounty program, other information related to security, and any other information that the developers find relevant.
```

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +- This function MAY not return the optional parameters.
```suggestion
- This function MAY return the optional parameters.
```
Wouldn't this be part of `SecurityInformation`

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +- This function MUST return atleast one item in the `contact_information` field's `Vec`. Furthurmore, the string should follow the following format `<contact_type>:<contact_information>`.
```suggestion
- This function MUST return at least one item in the `contact_information` field's `Vec`. Furthermore, the string should follow the following format `<contact_type>:<contact_information>`.
```

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +- This function MUST NOT return any empty strings. Optional parameters must return `None` if it is unnecessary.
```suggestion
- This function MUST NOT return any empty strings. Optional parameters MUST return `None` if it is unnecessary.
```

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +- This function MUST return atleast one item in the `preferred_languages`, if it is not `None`. Furthurmore, the string should only contain the `ISO 639-1` language code and nothing else.
```suggestion
- This function MUST return at least one item in the `preferred_languages`, if it is not `None`. Furthermore, the string should only contain the `ISO 639-1` language code and nothing else.
```

Perhaps a link to ISO 639-1's definition would be relevant here

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +- This function MAY return a link or the information directly for the following fields: `project_url`, `policy`, `encryption`, `source_code`, `auditors`, `acknowledgements`, `additional_information`.
```suggestion
- This function MAY return a link or the information directly for the following fields: `project_url`, `policy`, `encryption`, `source_code`, `auditors`, `acknowledgments`, `additional_information`.
```

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +- This function MUST return the information directly for the following fields: `name`, `contact_information`, `preferred_languages`, `source_release`, `source_revision`.
```suggestion
- This function MUST return the information directly for the following fields: `name`, `contact_information`, `preferred_languages`, `source_release`, and `source_revision`.
```

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +// Is this section necessary?
Is this meant to be here?

2024-02-13 04:36 UTC, bitzoic commented on standards/src11-security-information/README.md
> +The information is entirely self reported and as such might not be accurate. Accuracy of information cannot be enforced and as such, anyone using this information should be aware of that.
> "might not be accurate"

Isn't it defined in the standard that it must be up to date?

2024-02-14 10:27 UTC, SwayStar123 commented on standards/src11-security-information/README.md
> +The information is entirely self reported and as such might not be accurate. Accuracy of information cannot be enforced and as such, anyone using this information should be aware of that.
Yeah but people can lie lol, important to note that its entirely self reported, just because its on the blockchain doesnt make it verified or real

2024-02-19 22:10 UTC, dmihal submitted a review, later dismissed

2024-02-23 06:07 UTC, bitzoic reviewed
Just needs the examples and standard to be added to their respective workspace as well as a link to the standard in the source README

2024-02-23 06:07 UTC, bitzoic commented on standards/src11-security-information/README.md
> +- The struct MAY contain a link or the information directly for the following fields: `project_url`, `policy`, `encryption`, `source_code`, `auditors`, `acknowledgments`, `additional_information`.
```suggestion
- The struct MAY contain a URL or the information directly for the following fields: `project_url`, `policy`, `encryption`, `source_code`, `auditors`, `acknowledgments`, `additional_information`.
```

2024-02-23 06:07 UTC, bitzoic commented on standards/src11-security-information/README.md
> +- The struct MUST contain the information directly for the following fields: `name`, `contact_information`, `preferred_languages`, `source_release`, and `source_revision`.
Not sure how I feel about "directly". Maybe "The struct MUST contain the following information encoded as a `String` for the following fields:"?

2024-02-27 08:26 UTC, SwayStar123 commented on standards/src11-security-information/src/src11.sw
> +    /// The revision identifier of this build, usually a git sha that can be rebuilt to reproduce the same binary.
commit id (sha 256 hash)

2024-03-06 02:56 UTC, bitzoic commented on standards/src11-security-information/src/src11.sw
> +    /// The revision identifier of this build, usually a git sha that can be rebuilt to reproduce the same binary.
Can you make it say git commit id instead of git sha?

2024-03-12 02:28 UTC, bitzoic approved these changes

2024-03-12 15:52 UTC, merged