SRC-14 Simple Proxy Standard
FuelLabs/sway-standards pull request #94
Opened 2024-05-21 10:52 UTC by IGI-111

## Type of change

New Standard

## Changes

The following changes have been made:

- Add the SRC-14 standard specification, abi and examples

## Related Issues

https://github.com/FuelLabs/sway-rfcs/pull/39

2024-05-22 00:36 UTC, JoshuaBatty commented
Nice work, want a little bit more time to mull on the proposal but from my initial passes the syntax looks well thought out.

2024-05-22 03:27 UTC, bitzoic requested changes
Very cool!!

@SwayStar123 Could you please use this standard for the proxy work you are doing?

2024-05-22 03:27 UTC, bitzoic commented on standards/src/src14.sw
> +    ///
```suggestion
    ///
    /// # Arguments
    ///
    /// * `new_target`: [ContractId] - The new proxy contract to which all fallback calls will be passed.
    ///
```

2024-05-22 03:27 UTC, bitzoic commented on standards/src/src14.sw
> +    /// fn foo(contract: ContractId) {
```suggestion
    /// fn foo(contract_id: ContractId) {
```
`contract` is a reserved keyword so this will not compile

2024-05-22 03:27 UTC, bitzoic commented on standards/src/src14.sw
> +    ///     let contract_abi = abi(SRC14, contract);
```suggestion
    ///     let contract_abi = abi(SRC14, contract_id.bits());
```
👀 https://github.com/FuelLabs/sway/issues/5695

2024-05-22 03:27 UTC, bitzoic commented on SRCs/src-14.md
> +A proxy contract SHOULD maintain the address of its target in its storage and it SHOULD base proxy specific storage fields at `sha256("storage_SRC14")` to avoid collisions with target storage.
This is currently suggested as SHOULD under the required behaviors section. Don't we want this to be required as not setting the namespace can cause unintended consequences? Is there a case where the namespace should differ?

2024-05-22 03:27 UTC, bitzoic commented on SRCs/src-14.md
> +# Simple Upgradable Proxies
Is there a reason why the standard is labeled as "Simple" Upgradable Proxies? Is there intent for a future proxy that is in some way more complex and builds off SRC14? What would be the distinction between a simple and complex proxy standard?

2024-05-22 03:29 UTC, bitzoic commented
Dependent on https://github.com/FuelLabs/sway-standards/pull/95

2024-05-22 05:53 UTC, SwayStar123 commented on SRCs/src-14.md
> +This method SHOULD implement access controls such that the target can only be changed by a user that possesses the right permissions (typically the proxy owner).
should this 'SHOULD' not be a 'MAY'?

2024-05-22 08:39 UTC, IGI-111 commented on SRCs/src-14.md
> +A proxy contract SHOULD maintain the address of its target in its storage and it SHOULD base proxy specific storage fields at `sha256("storage_SRC14")` to avoid collisions with target storage.
It's a good practice, but not absolutely necessary to have a functioning proxy, and more complex implementations may actually want some overlap between the proxy and target storage definitions so there's some communication between the two.

UUPS requires the address to be at a particular location but that's an artifact of how it's designed, since we have the update method be part of the proxy we don't have to be opinionated about how it's stored.

However, come to think of it, it would be helpful to have the address location standardized in the future for tooling to map out proxies more easily.

I think I can come up with something clearer here.

2024-05-22 08:44 UTC, IGI-111 commented on SRCs/src-14.md
> +# Simple Upgradable Proxies
I guess what I meant is that it's not a Diamond, it doesn't have any sophisticated logic to decide what to call, it's just a single address in storage to passthrough.

We may want something like ERC-2535 in the future, and I suppose that would be a "complex" proxy.

2024-05-22 14:56 UTC, luizstacio commented on examples/src14-simple-proxy/owned/src/owned.sw
> +    run_external(storage.target.read())
Does `run_external` automatically forward params for the target code function?

Ex.: `increament(amount: u64) -> u64`

2024-05-22 16:05 UTC, IGI-111 commented on examples/src14-simple-proxy/owned/src/owned.sw
> +    run_external(storage.target.read())
Yes, but this is actually tied into a limitation of how LDC currently works. The CALL frame parameters are placed relative to the frame pointer, and since LDC execution does not move the frame pointer, they are unchanged.

This means that you can only proxy into functions that have the same signature as you, but for fallback this isn't a problem because it forwards everything.

2024-05-23 07:36 UTC, bitzoic commented on SRCs/src-14.md
> +The proxy contract MUST maintain the address of its target in its storage at slot `0x7bb458adc1d118713319a5baa00a2d049dd64d2916477d2688d76970c898cd55` (equivalent to `sha256("storage_SRC15_0")`).
```suggestion
The proxy contract MUST maintain the address of its target in its storage at slot `0x7bb458adc1d118713319a5baa00a2d049dd64d2916477d2688d76970c898cd55` (equivalent to `sha256("storage_SRC14_0")`).
```

2024-05-24 00:12 UTC, JoshuaBatty commented
Are we missing a section about auto generating the proxy contract byte code? I'm not 100% clear how that part is going to be implemented.

2024-05-24 07:09 UTC, SwayStar123 submitted a review, later dismissed

2024-05-25 05:21 UTC, SwayStar123 commented on examples/src14-simple-proxy/minimal/src/minimal.sw
> +    // target is as sha256("storage_SRC14_0")
What does this mean? Do you mean to use `at` here? (Same sentence is in the second example too)

2024-05-25 14:44 UTC, IGI-111 commented on examples/src14-simple-proxy/minimal/src/minimal.sw
> +    // target is as sha256("storage_SRC14_0")
It's a typo, I'll correct both instances.

2024-05-26 06:13 UTC, SwayStar123 submitted a review, later dismissed

2024-05-27 17:41 UTC, IGI-111 commented on SRCs/src-14.md
> +The proxy contract MUST maintain the address of its target in its storage at slot `0x7bb458adc1d118713319a5baa00a2d049dd64d2916477d2688d76970c898cd55` (equivalent to `sha256("storage_SRC14_0")`).
It's that way for compatibility purposes with the current implementation of namespacing, but the `standards` package provides a constant so that with the new syntax you'll be able to do:

```sway
use standards::src14::SRC14_TARGET_STORAGE;
storage {
    target in SRC14_TARGET_STORAGE : b256 = TARGET_VALUE;
}
```

2024-05-27 18:00 UTC, IGI-111 commented on SRCs/src-14.md
> +Unlike in UUPS, this standard requires that the upgrade function is part of the proxy and not its target.
I think I may as well link to the EIP here too

2024-05-28 01:39 UTC, kayagokalp approved these changes
👌

2024-05-28 01:39 UTC, kayagokalp commented on SRCs/src-14.md
> +The proxy contract MUST maintain the address of its target in its storage at slot `0x7bb458adc1d118713319a5baa00a2d049dd64d2916477d2688d76970c898cd55` (equivalent to `sha256("storage_SRC14_0")`).
cc @JoshuaBatty looks like sway standart is already going to enforce this. So we do not need to worry about this one as long as the user specified custom proxy contracts are in line with the standard.

2024-05-28 03:22 UTC, bitzoic approved these changes

2024-05-28 04:04 UTC, JoshuaBatty approved these changes

2024-05-28 11:46 UTC, merged